import type { GetStaticProps, NextPage } from "next";
import { serverSideTranslations } from "next-i18next/serverSideTranslations";
import Head from "next/head";
import Navbar from "@/shared/components/general/Navbar";
import Footer from "@/shared/components/general/Footer";

const TermsOfService: NextPage = () => {
  const sections = [
    { title: "1. Acceptance of Terms", content: 'By accessing and using <strong class="text-indigo-400">Blayer</strong> ("the Service"), you accept these Terms of Service.' },
    { title: "2. Description of Service", content: 'Blayer is a free API integration code generator tool. It generates TypeScript code based on API endpoint data. All processing is done locally in your browser — no data is sent to our servers.' },
    { title: "3. User Responsibilities", content: 'Use the Service only for lawful purposes. Do not disrupt the Service. Take responsibility for the generated code.' },
    { title: "4. Intellectual Property", content: 'The Blayer application (design, code, branding) is owned by Dzikri Alan. The code generated by Blayer based on your inputs is owned by you.' },
    { title: "5. Third-Party Services", content: 'We are not responsible for third-party services linked from our Service, including Google AdSense.' },
    { title: "6. Advertising", content: 'The Service is supported by Google AdSense advertising. Ads help us keep the Service free.' },
    { title: "7. Disclaimer of Warranties", content: 'The Service is provided "as is" without warranties of any kind.' },
    { title: "8. Limitation of Liability", content: 'Blayer shall not be liable for indirect, incidental, or consequential damages from your use of the Service.' },
    { title: "9. Changes to Terms", content: 'We reserve the right to modify these Terms. Continued use after changes constitutes acceptance.' },
    { title: "10. Governing Law", content: 'These Terms are governed by the laws of Indonesia.' },
    { title: "11. Contact Us", content: 'Questions? Contact us at <a href="mailto:dzikripride@gmail.com" class="text-indigo-400 hover:underline">dzikripride@gmail.com</a>.' },
  ];

  return (
    <>
      <Head>
        <title>Terms of Service - Blayer</title>
        <meta name="description" content="Terms of Service for Blayer - API Integration Code Generator" />
      </Head>
      <div className="min-h-screen w-full flex flex-col text-[#F5F1EA] bg-[#020617]">
        <div className="fixed inset-0 z-0 overflow-hidden pointer-events-none">
          <div className="absolute top-[-10%] left-[-10%] w-[60%] h-[60%] bg-indigo-600/10 blur-[140px] rounded-full"></div>
          <div className="absolute bottom-[-10%] right-[-10%] w-[50%] h-[60%] bg-purple-600/10 blur-[130px] rounded-full"></div>
          <div className="absolute inset-0 opacity-[0.05]" style={{ backgroundImage: 'linear-gradient(#4f46e5 1px, transparent 1px), linear-gradient(90deg, #4f46e5 1px, transparent 1px)', backgroundSize: '40px 40px' }}></div>
        </div>

        <Navbar />
        <div className="h-16 shrink-0"></div>

        <main className="flex-1 relative z-10 py-12 px-6">
          <div className="max-w-3xl mx-auto">
            <h1 className="text-3xl font-extrabold text-white mb-2 tracking-tight">Terms of Service</h1>
            <p className="text-slate-500 text-sm mb-10">Last updated: April 25, 2026</p>

            <div className="space-y-8 text-slate-300 text-[14px] leading-relaxed">
              {sections.map((section) => (
                <section key={section.title}>
                  <h2 className="text-lg font-bold text-white mb-3">{section.title}</h2>
                  <p dangerouslySetInnerHTML={{ __html: section.content }} />
                </section>
              ))}
            </div>
          </div>
        </main>

        <Footer />
      </div>
    </>
  );
};

export const getStaticProps: GetStaticProps = async ({ locale }) => ({
  props: {
    ...(await serverSideTranslations(locale ?? "en", ["common"])),
  },
});

export default TermsOfService;
